### ISSUE TITLE
Ottawa ruby logo

### ISSUE THREAD

**Issue by arthurnn** [ottawaruby/ottawaruby.github.com#1]
Seems like the logo on ottawaruby organization was lost. Maybe a gravatar issue?

**Comment by kurtfunai** [comment]
:+1:

**Comment by kurtfunai** [comment]
From website:
![logo](https://cloud.githubusercontent.com/assets/566763/2855766/b9c0f83e-d160-11e3-9ef6-be74643713f3.png)

**Comment by M7** [comment]
Oops! Sorry, forgot to update this issue. This was actually fixed a while ago. Thanks for the head's up @arthurnn, for the logo @kurtfunai, and for closing the issue @mgingras! :)

**Comment by kurtfunai** [comment]
:clap:  :smile:
